# Google App Engine Configuration for Frontend (React)

runtime: nodejs18

# Environment variables
env_variables:
  REACT_APP_API_URL: "https://g1sivesh.appspot.com"
  NODE_ENV: "production"

# Automatic scaling configuration
automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.6

# Resource limits
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

# Handlers for React app
handlers:
  # Static files
  - url: /static
    static_dir: build/static
    secure: always

  # All other routes go to React app
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    secure: always

# Skip files that shouldn't be deployed
skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^(.*/)?(tests|test)/.*$
  - ^(.*/)?backend/.*$
  - ^(.*/)?\.git/.*$
  - ^(.*/)?\.gitignore$
  - ^(.*/)?README\.md$
  - ^(.*/)?DEPLOYMENT\.md$
  - ^(.*/)?TEST.*\.md$
  - ^(.*/)?FINAL_STATUS\.md$
  - ^(.*/)?COMPREHENSIVE_TEST_RESULTS\.md$
  - ^(.*/)?start\.sh$
  - ^(.*/)?build\.sh$
  - ^(.*/)?deploy\.sh$
  - ^(.*/)?app\.yaml$
  - ^(.*/)?render\.yaml$
