# Google App Engine Configuration for Backend (FastAPI)

runtime: python39

# Environment variables
env_variables:
  MONGODB_URL: "mongodb+srv://your-username:your-password@your-cluster.mongodb.net/invoice_management?retryWrites=true&w=majority"
  SECRET_KEY: "your-secret-key-here"
  ENVIRONMENT: "production"
  CORS_ORIGINS: "https://g1sivesh.appspot.com"

# Automatic scaling configuration
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

# Health check configuration
health_check:
  enable_health_check: true
  check_interval_sec: 30
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
  restart_threshold: 60

# Resource limits
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

# Network configuration
network:
  session_affinity: true

# Handlers for different routes
handlers:
  # API routes
  - url: /api/.*
    script: auto
    secure: always

  # Static files (if any)
  - url: /static
    static_dir: static
    secure: always

  # Default handler
  - url: /.*
    script: auto
    secure: always

# Skip files that shouldn't be deployed
skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^(.*/)?(tests|test)/.*$
  - ^(.*/)?node_modules/.*$
  - ^(.*/)?frontend/.*$
  - ^(.*/)?\.git/.*$
  - ^(.*/)?\.gitignore$
  - ^(.*/)?README\.md$
  - ^(.*/)?DEPLOYMENT\.md$
  - ^(.*/)?TEST.*\.md$
  - ^(.*/)?FINAL_STATUS\.md$
  - ^(.*/)?COMPREHENSIVE_TEST_RESULTS\.md$
  - ^(.*/)?start\.sh$
  - ^(.*/)?build\.sh$
  - ^(.*/)?deploy\.sh$
  - ^(.*/)?package\.json$
  - ^(.*/)?render\.yaml$
