services:
  # Backend Service
  - type: web
    name: invoicing-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: invoicing_db
      - key: ENVIRONMENT
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0

  # Frontend Service
  - type: web
    name: invoicing-frontend
    env: static
    plan: free
    buildCommand: cd frontend && yarn install && yarn build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_BACKEND_URL
        fromService:
          type: web
          name: invoicing-backend
          property: host
